spring:
  datasource:
    dynamic:
      primary: mysql           # 默认数据源
      strict: false
      datasource:
        mysql:
          url: jdbc:mysql://192.168.99.200:3306/mall_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
          username: root
          password: ymj521.YY
          driver-class-name: com.mysql.cj.jdbc.Driver
        oracle:
          url: jdbc:oracle:thin:@192.168.99.200:1521/ORCLPDB1?allowPublicKeyRetrieval=true&useSSL=false
          username: root
          password: ymj521.YY
          driver-class-name: oracle.jdbc.OracleDriver
        clickhouse:
          url: jdbc:clickhouse://192.168.99.200:8123/default?allowPublicKeyRetrieval=true&useSSL=false
          username: default
          password: ymj521.YY
          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

  redis:
    host: 192.168.99.200
    port: 6379
    password: ymj521.YY
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  data:
    mongodb:
      uri: mongodb://root:ymj521.YY@192.168.99.200:27017/mall_logs?authSource=admin&connectTimeoutMS=50000&socketTimeoutMS=50000&serverSelectionTimeoutMS=500008&allowPublicKeyRetrieval=true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update        # 开发阶段自动建表
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    com.baomidou.dynamic.datasource: INFO

# Knife4j 配置
knife4j:
  enable: true                             # 开启 Knife4j 增强功能
  production: false                        # 生产环境设为 true 可屏蔽资源
  setting:
    language: zh-CN                         # 界面语言
    enableFooter: false                     # 是否显示页脚
